import React, { useEffect, useState } from 'react';
import { Clock, Search, AlertCircle, CheckCircle2, XCircle, Plus, Edit2, Trash2, X } from 'lucide-react';
import { AttendanceRecord, Business, PayrollPeriod, AttendanceStatus, Employee } from '../../types';
import { api } from '../../services/api';

type Row = AttendanceRecord & { employeeName:string; employeeIdCode:string; businessName:string };
const empty={employeeId:'',date:'',timeIn:'',breakOut:'',breakIn:'',timeOut:'',lateMinutes:'0',totalWorkMinutes:'0',status:'present'};

export const AttendanceManagement: React.FC = () => {
  const [records,setRecords]=useState<Row[]>([]),[businesses,setBusinesses]=useState<Business[]>([]),[periods,setPeriods]=useState<PayrollPeriod[]>([]),[employees,setEmployees]=useState<(Employee & {businessName:string})[]>([]);
  const [selectedPeriodId,setSelectedPeriodId]=useState(''),[selectedBusinessId,setSelectedBusinessId]=useState('all'),[selectedDate,setSelectedDate]=useState(''),[search,setSearch]=useState(''),[loading,setLoading]=useState(true);
  const [modal,setModal]=useState(false),[editId,setEditId]=useState<string|null>(null),[form,setForm]=useState<any>(empty);

  const loadAttendance=async()=>{if(!selectedPeriodId){setRecords([]);return;}setLoading(true);try{const a=await api.admin.getAttendance({periodId:selectedPeriodId,businessId:selectedBusinessId!=='all'?selectedBusinessId:undefined,date:selectedDate||undefined});setRecords(a);}catch(err){console.error(err);setRecords([]);}finally{setLoading(false);}};
  useEffect(()=>{Promise.all([api.admin.getBusinesses(),api.admin.getPeriods(),api.admin.getEmployees()]).then(([b,p,e])=>{setBusinesses(b);setPeriods(p);setEmployees(e);const active=p.find(x=>x.status==='open'||x.status==='for_approval')||p[0];setSelectedPeriodId(active?.id||'');}).catch((err)=>console.error(err));},[]);
  useEffect(()=>{loadAttendance();},[selectedPeriodId,selectedBusinessId,selectedDate]);

  const iso=(v:string)=>v?new Date(v).toISOString():'';
  const localValue=(v?:string)=>v?new Date(v).toLocaleString('sv-SE',{timeZone:'Asia/Manila'}).replace(' ','T').slice(0,16):'';
  const save=async(e:React.FormEvent)=>{e.preventDefault();try{const selectedPeriod=periods.find(p=>p.id===selectedPeriodId);if(!selectedPeriod)throw new Error('Please select a payroll cut-off period.');if(!editId&&(form.date<selectedPeriod.startDate||form.date>selectedPeriod.endDate))throw new Error('The attendance date must be within the selected payroll cut-off period.');const payload={employeeId:form.employeeId,date:form.date,payrollPeriodId:selectedPeriodId,timeIn:form.timeIn?iso(form.timeIn):null,breakOut:form.breakOut?iso(form.breakOut):null,breakIn:form.breakIn?iso(form.breakIn):null,timeOut:form.timeOut?iso(form.timeOut):null,lateMinutes:Number(form.lateMinutes||0),totalWorkMinutes:Number(form.totalWorkMinutes||0),status:form.status};if(editId)await api.admin.updateAttendance(editId,payload);else await api.admin.addAttendance(payload);setModal(false);await loadAttendance();}catch(err:any){alert(err.message||'Unable to save attendance.')}};
  const deleteAttendance = async (record: Row) => {
    if (!confirm(`Delete the attendance record for ${record.employeeName} on ${record.date}? This action cannot be undone.`)) return;
    try {
      await api.admin.deleteAttendance(record.id);
      await loadAttendance();
    } catch (err:any) {
      alert(err.message || 'Unable to delete attendance.');
    }
  };
  const badge=(s:AttendanceStatus)=>s==='present'?<span className="text-emerald-400"><CheckCircle2 className="inline w-3.5 h-3.5"/> Present</span>:s==='late'?<span className="text-amber-400"><Clock className="inline w-3.5 h-3.5"/> Late</span>:s==='absent'?<span className="text-red-400"><XCircle className="inline w-3.5 h-3.5"/> Absent</span>:s==='invalid'?<span className="text-red-400"><AlertCircle className="inline w-3.5 h-3.5"/> Invalid</span>:<span className="text-slate-400"><AlertCircle className="inline w-3.5 h-3.5"/> Incomplete</span>;
  const filtered=records.filter(r=>r.employeeName.toLowerCase().includes(search.toLowerCase())||r.employeeIdCode.toLowerCase().includes(search.toLowerCase()));
  const input="w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white";
  return <div className="space-y-6">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-white">Attendance Logs</h1><p className="text-sm text-slate-400 mt-1">Review, add, and correct employee attendance records.</p></div><button onClick={()=>{setEditId(null);setForm({...empty,employeeId:employees[0]?.id||'',date:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Manila'})});setModal(true)}} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-sm font-medium"><Plus className="w-4 h-4"/> Add Attendance</button></div>
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
      <div><label className="block text-xs text-slate-400 mb-1">Search Employee</label><div className="relative"><Search className="w-4 h-4 text-slate-500 absolute left-3 top-2.5"/><input className={input+" pl-9"} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or ID"/></div></div>
      <div><label className="block text-xs text-slate-400 mb-1">Business</label><select className={input} value={selectedBusinessId} onChange={e=>setSelectedBusinessId(e.target.value)}><option value="all">All Businesses</option>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>
      <div><label className="block text-xs text-slate-400 mb-1">Payroll Cut-Off Period</label><select required className={input} value={selectedPeriodId} onChange={e=>{setSelectedPeriodId(e.target.value);setSelectedDate('')}}><option value="" disabled>Select a cut-off period</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name} ({p.startDate} to {p.endDate})</option>)}</select></div>
      <div><label className="block text-xs text-slate-400 mb-1">Date</label><input type="date" className={input} value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/></div>
    </div>
    <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm text-slate-300"><thead className="bg-slate-950/80 text-xs uppercase text-slate-400"><tr>{['Date','Employee','Business','Time In','Break','Time Out','Late/Undertime/Overbreak','Hours','Status',''].map(h=><th key={h} className="py-3 px-4">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-800/80">{loading?<tr><td colSpan={10} className="py-8 text-center text-slate-500">Loading…</td></tr>:filtered.length===0?<tr><td colSpan={10} className="py-8 text-center text-slate-500">No attendance logs found.</td></tr>:filtered.map(a=><tr key={a.id} className="hover:bg-slate-800/40"><td className="py-3 px-4 font-mono text-white">{a.date}</td><td className="py-3 px-4"><div className="font-semibold text-white">{a.employeeName}</div><div className="text-xs text-slate-500">{a.employeeIdCode}</div></td><td className="py-3 px-4 text-xs">{a.businessName}</td><td className="py-3 px-4 font-mono text-xs">{a.timeIn?new Date(a.timeIn).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit'}):'—'}</td><td className="py-3 px-4 font-mono text-xs">{a.breakOut?new Date(a.breakOut).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit'}):'—'}{a.breakIn?' – '+new Date(a.breakIn).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit'}):''}</td><td className="py-3 px-4 font-mono text-xs">{a.timeOut?new Date(a.timeOut).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila',hour:'2-digit',minute:'2-digit'}):'—'}</td><td className="py-3 px-4 text-xs" title={'Late: '+(a.lateMinutes||0)+' min • Undertime: '+(a.undertimeMinutes||0)+' min • Overbreak: '+(a.overbreakMinutes||0)+' min'}>{(a.varianceMinutes||0)>0?<span className="font-semibold text-amber-400">+{a.varianceMinutes} mins</span>:<span className="text-slate-500">0 min</span>}</td><td className="py-3 px-4 text-xs">{a.totalWorkMinutes>0?((a.totalWorkMinutes/60).toFixed(2).replace(/0+$/,'').replace(/\.$/,''))+' hrs':'—'}</td><td className="py-3 px-4 text-xs">{badge(a.status)}</td><td className="py-3 px-4 text-right"><button onClick={()=>{setEditId(a.id);setForm({employeeId:a.employeeId,date:a.date,timeIn:localValue(a.timeIn),breakOut:localValue(a.breakOut),breakIn:localValue(a.breakIn),timeOut:localValue(a.timeOut),lateMinutes:String(a.lateMinutes||0),totalWorkMinutes:String(a.totalWorkMinutes||0),status:a.status});setModal(true)}} className="p-2 text-blue-400 hover:text-blue-300"><Edit2 className="w-4 h-4"/></button><button onClick={()=>deleteAttendance(a)} className="p-2 text-red-400 hover:text-red-300" title="Delete"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div></div>
    {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80"><div className="w-full max-w-lg bg-slate-900 border border-slate-800 rounded-xl shadow-2xl"><div className="flex items-center justify-between p-4 border-b border-slate-800"><h2 className="font-semibold text-white">{editId?'Edit Attendance':'Add Attendance'}</h2><button onClick={()=>setModal(false)}><X className="w-5 h-5 text-slate-400"/></button></div><form onSubmit={save} className="p-4 space-y-3">
      {!editId&&<div><label className="block text-xs text-slate-400 mb-1">Employee</label><select required className={input} value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}>{employees.map(e=><option key={e.id} value={e.id}>{e.fullName} ({e.employeeId})</option>)}</select></div>}
      <div><label className="block text-xs text-slate-400 mb-1">Duty Date</label><input required type="date" className={input} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></div>
      <div className="grid grid-cols-2 gap-3">{[['timeIn','Time In'],['breakOut','Break Out'],['breakIn','Break In'],['timeOut','Time Out']].map(([k,l])=><div key={k}><label className="block text-xs text-slate-400 mb-1">{l}</label><input type="datetime-local" className={input} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}</div>
      <div className="grid grid-cols-3 gap-3"><div><label className="block text-xs text-slate-400 mb-1">Late Minutes</label><input type="number" min="0" className={input} value={form.lateMinutes} onChange={e=>setForm({...form,lateMinutes:e.target.value})}/></div><div><label className="block text-xs text-slate-400 mb-1">Work Minutes</label><input type="number" min="0" className={input} value={form.totalWorkMinutes} onChange={e=>setForm({...form,totalWorkMinutes:e.target.value})}/></div><div><label className="block text-xs text-slate-400 mb-1">Status</label><select className={input} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="incomplete">Incomplete</option></select></div></div>
      <div className="flex justify-end gap-2 pt-3 border-t border-slate-800"><button type="button" onClick={()=>setModal(false)} className="px-4 py-2 rounded-lg bg-slate-800 text-slate-300">Cancel</button><button className="px-4 py-2 rounded-lg bg-blue-600 text-white font-medium">{editId?'Save Changes':'Add Attendance'}</button></div>
    </form></div></div>}
  </div>;
};
